Repository 2201gh-capstone-banana/2201gh-capstone, pull requests merged in 2022-03, with the labels that each got.

#17 fs-app-template-added
  .babelrc
  .gitignore
  LICENSE
  client/App.js
  client/Routes.js
  client/components/AuthForm.js
  client/components/Home.js
  client/components/Home.spec.js
  client/components/Navbar.js
  client/history.js
  client/index.js
  client/store/auth.js
  client/store/auth.spec.js
  client/store/index.js
  package.json
  public/favicon.ico
  public/index.html
  public/style.css
  script/seed.js
  server/api/index.js
  server/api/users.js
  server/api/users.spec.js
  server/app.js
  server/auth/index.js
  server/db/db.js
  server/db/index.js
  server/db/models/User.js
  server/db/models/User.spec.js
  server/index.js
  webpack.config.js
Labels: good first issue

#18 removed all instances of fs-app-template
  client/components/Navbar.js
  package.json
  public/index.html
Labels: good first issue

#24 seed file updated to include firstName lastName
  script/seed.js
  server/db/models/User.js
Labels: bug

#25 Imported teachable machine model with tensorflow.js
  client/Routes.js
  client/components/Home.js
  client/components/utilities.js
  package.json
  public/metadata.json
  public/model.json
  public/weights.bin
Labels: good first issue, MVP, Tier 1

#38 Added letters r-z as well as an index file in the letters folder
  client/components/Main.js
  client/components/letters/index.js
  client/components/letters/letterR.js
  client/components/letters/letterS.js
  client/components/letters/letterT.js
  client/components/letters/letterU.js
  client/components/letters/letterV.js
  client/components/letters/letterW.js
  client/components/letters/letterX.js
  client/components/letters/letterY.js
  client/components/letters/letterZ.js
  package.json
Labels: MVP, Tier 1

#48 Optimization of main code
  client/components/Main.js
  client/components/letters/index.js
  client/components/letters/letterA.js
  client/data/index.js
Labels: bug, enhancement, MVP, Tier 1

#49 Home page2.0
  client/Routes.js
  client/components/Home.css
  client/components/Home.js
  client/components/LandingPage.js
  client/components/Learning.js
  client/components/Navbar.css
  client/components/Navbar.js
  package.json
Labels: enhancement, MVP, Tier 1

#58 Signout
  client/Routes.js
  client/components/Idle.js
  client/components/Navbar.js
  client/store/auth.js
  css/idle.css
  css/index.css
  package.json
Labels: bug, enhancement, MVP, Tier 1

#62 Removed some console.logs from Main.js
  client/components/Main.js
Labels: enhancement

#65 edit css for navbar and home page only
  client/components/Home.css
  client/components/Home.js
  client/components/Navbar.css
  client/components/Navbar.js
  public/Bee.mp4
Labels: enhancement

#76 Wordle board is visually up and running
  client/Routes.js
  client/components/Wordle/LetterCell.js
  client/components/Wordle/WordRow.js
  client/components/Wordle/WordleBoard.js
  client/components/Wordle/wordleUtilities/data/index.js
  client/components/Wordle/wordleUtilities/index.js
  client/components/WordleApp.js
  client/components/WordleDetection.js
  client/data/index.js
  client/store/wordle.js
  css/index.css
  css/wordle.css
  script/answerBank.js
  script/seed.js
  server/api/index.js
  server/api/words.js
  server/db/index.js
  server/db/models/Answer.js
Labels: MVP, Tier 1

#83 Backend Work plus cleaning up Wordle functional components
  client/Routes.js
  client/components/LeaderBoard.js
  client/components/Main.js
  client/components/Modal.css
  client/components/Modal.js
  client/components/Sidebar.css
  client/components/Sidebar.js
  client/components/SidebarData.js
  client/components/Wordle/LetterCell.js
  client/components/Wordle/WordRow.js
  client/components/Wordle/WordleBoard.js
  client/components/Wordle/wordleUtilities/index.js
  client/components/WordleApp.js
  client/components/WordleDetection.js
  client/components/letters/letterP.js
  client/components/letters/letterQ.js
  client/components/letters/letterR.js
  client/components/letters/letterS.js
  client/components/letters/letterT.js
  client/components/letters/letterU.js
  client/components/letters/letterV.js
  client/components/letters/letterW.js
  client/components/letters/letterX.js
  client/components/letters/letterY.js
  client/components/letters/letterZ.js
  client/store/auth.js
  client/store/checkValidGuess.js
  client/store/index.js
  client/store/wordle.js
  css/wordle.css
  package.json
  script/seed.js
  server/api/index.js
  server/api/securityMiddleware.js
  server/api/users.js
  server/api/wordleGames.js
  server/api/words.js
  server/auth/index.js
  server/db/models/AcceptedGuess.js
  server/db/models/User.js
Labels: MVP, Tier 1

#86 Connected wordle board to the redux store
  client/components/Wordle/LetterCell.js
  client/components/Wordle/WordRow.js
  client/components/Wordle/WordleBoard.js
  client/components/Wordle/wordleUtilities/index.js
  client/components/WordleApp.js
  client/components/WordleDetection.js
  client/store/index.js
  client/store/targetWord.js
  client/store/wordle.js
Labels: MVP, Tier 1

#91 Work on updating the submit + add letter routes to have a submit button
  client/components/Learning.js
  client/components/Wordle/LetterCell.js
  client/components/Wordle/WordleBoard.js
  client/components/WordleApp.js
  client/components/WordleDetection.js
  client/components/phrases/delete.js
  client/store/checkValidGuess.js
  client/store/targetWord.js
  client/store/wordle.js
  css/cheatSheet.css
  script/seed.js
  server/api/securityMiddleware.js
  server/api/users.js
  server/api/wordleGames.js
  server/auth/index.js
  server/db/models/User.js
Labels: MVP, Tier 1

#93 updated some funcitonality
  client/App.js
  client/Routes.js
  client/components/Home.js
  client/components/LeaderBoard.js
  client/components/Learning.js
  client/components/Main.js
  client/components/Modal.js
  client/components/Sidebar.js
  client/components/Wordle/EndGame.js
  client/components/Wordle/LetterCell.js
  client/components/Wordle/LosingPage.js
  client/components/Wordle/WordleBoard.js
  client/components/WordleApp.js
  client/components/WordleDetection.js
  client/store/checkValidGuess.js
  client/store/wordle.js
  client/utilities/pose.js
Labels: MVP, Tier 1
